### PR TITLE
Better BlockDome init

### PR DESCRIPTION
**Pull request by TheLoneWolfling**
This way it'll actually load all blocks, even if there are gaps in the
block IDs.

### CODE REVIEW

**Comment by BrainSlugs83** [comment]
Code looks good; made some formatting and refactoring changes and merged.

**Comment by TheLoneWolfling** [comment]
Looks good. Though I tend to stay away from that style of coding in Java - there ends up being enough going on behind the scenes that it can be... difficult, shall I say, to diagnose performance issues.  Or rather to see where the actual complexity is. So many temporary objects. And Minecraft is slow enough at loading as it is.

Though it shouldn't be an issue in this case, hopefully.

**Comment by BrainSlugs83** [comment]
Yeah, I agree -- I definitely made some performance trade-offs here -- I'm hoping that in this case it ends up not being a big deal (it doesn't seem noticeably slower on vanilla, anyway) -- and I know the Windows JRE isn't the most performant run-time ever, but, I've been reading that the GC is getting better for short-lived throw-away objects... so, yeah, we'll see.

Btw, I originally had getAllBlocks refactored to be identical to your code above (save for the domeBlocks check) -- if it ends up being a huge issue, I'll probably just put it back to that state.

**Comment by BrainSlugs83** [comment]
I'm gonna have to check if MCP 1.8 supports Java 1.8 yet -- would be nice to switch to Java native streams (as opposed to trying to emulate LINQ in a language that doesn't have extension methods -- also, doesn't 1.8 have lambda methods?).

**Comment by BrainSlugs83** [comment]
Looks like it does! -- Woot.  https://github.com/MinecraftForge/MinecraftForge/issues/1003

**Comment by TheLoneWolfling** [comment]
I'd be wary of using Java 8-only features. And lambdas can be... less than fun. In particular, the stack traces. Oh dear the stack traces.

**Comment by BrainSlugs83** [comment]
Why weary? -- compatibility or... something else?

**Comment by BrainSlugs83** [comment]
(Not particularly thrilled with Java's stack traces at the moment anyway...)

**Pull request merged**
